# Use postgres/example user/password credentials
version: '3.1'

services:

  investor:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 13724

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080